[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/login"
  to = "/login"
  status = 200
  force = true

[[redirects]]
  from = "/register"
  to = "/register"
  status = 200
  force = true
